server:
  port: 2021

spring:
  #mail配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    password: HXSKRBCFXOPZNACR
    username: q18580566944@163.com
    port: 25

  #rabbitmq配置
  rabbitmq:
    username: admin
    password: admin
    host: 127.0.0.1
    port: 5672
    #    消息确认回调
    publisher-confirm-type: correlated
    #    消息失败回调
    publisher-returns: true